---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgB5d7WazHBIat5sb16L4xC8xhgWQka36o5T+Ozyk0MBMAQjw0y2e68jKOfDEEcrSEXJ/DvrfEfHeGF2Jh1vXH1q7L2aOTg6RV97Y2npkrVYrrIWqCPjlzVi14llRl8BJnjGhQ0V/s+1vOEzUkmRttxsHfz9OmOrUHX7ZrMa6XEgW9+4MQwHYTrOpINOV+EIglRQahyHUB1NPGojVBqiOLhq2VvRjJ04BoBSpNT31eyAvoRxZacz9zjuXlcqaH+z6hlOlkSreIStHCeDI0ZcmjOxuKc1gsIXG40tGNH1XOwdjsOTupO5MA5fp+zHr+a7ISTeiYvLheNPDsWdTLhyaLPnddjsf0Pc6gA/VklFWD7P4RbhNqAZqc6idWEePzoqizvexn35qYDLcB/XmCAwW1u3dMaNZs4Rq34aoT2RFtqZsyayoiDUnuM0DJpLCVK1aEADC4oLJpsNWxi6/kR/JF388MBOc6ccMoEbjsdPTAfzxjmlf6LqoZSO2/pMoeglGuAID2InmarlSseSfYp7ySOvSHQgv/rijwAIcsvsw33boiSA0+X8PkM/7Vohk0H+6xWLr2oItr29pDkKWeJDT3DVQn85Ci6ej7h3Yo81r6sCAOgpPbjvu4mmeJT5am65H52f4zbYJuki3P37nwTpiDX4QGaKui19502vrqYFYx2jGekNgMkI1yA+l5COnIe39AoDe27WjUezig8=
    STRIPE_API_KEY: AgDVdm5tWF96WcBoRenOYnPia/ZwJA3eXJ+PWc40vsOwdJbRc+NtfJeyKnIgO1NUhKq/Rultg7QW4K5r/auQxruX8pQ52iDhEZ1cJqrdvstIizLcHRycijL4nln39ga4wmpw0fNRqujX/bQsvv/7P3AWPgABqn6yGo4FOGrqf3EY1rURaMjHyJqF6/yjTlnQrGVkXohp1/gRVX/iaXLe/zehgvBgF2sZsD1yRSrW69Uu9XIt4ogE+uccUzh3rUo+OWz7ZfiyBVr9CM2Gbc0ZrsWdt4+vCEjGAvkKtGgK4XIc/dbKargd5dWIBAFXqd1Jq4LKNwNdcCo0FpzLqcdOJ6ovkQkxL0tbQP97izOLx5Q2TnGnwCnlxCjwPkkohmDNsfVmY/rCeqpOotCQ2OvtnJ18RenhLsMeVErOeGC92x1eZ1bE+ilrq48aSlxnHwuXvy6CYM6k3ytH89H27GjMRwllmrSCRUGIe5l3hbMrgFEc9gYSMVHDO6lyZtBCPzH7Vfx52xgHsT7Az9b7ZUZOpdphhkL/8VFktOf9ptp6mGeUgm8E3t+L/oLzIm9b0bcBv+JE2RhunBe2v5UxqJcwPSYmRIgVdJkZhipeZZv2nH2YeYF0QKSmykdrbLYCzTMVYEwx/QtEJEYKkvLLBbSsW2fT8lsdqkrTSLwrsJh0S/5EDBH/Y7RbNMvw0g5ZH9kSVRnK0O9/icxGejSX/CE=
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
